### ISSUE TITLE
Being shot can knock you down

### ISSUE THREAD

**Issue by Rakune** [kachnov/WW13#126]
I thought it would be nice if there was a little chance (10-25%) chance to be knocked down for a second when you get shot. Or that the chance depends where they're hit, 15% for the chest, 25% for the legs, 10% for the arms. Also, this chance reduced when the person wears some kind of armor. Basically a way to give it a little more realism and also be able to stagger people since even if you have advantage and can totally kill someone with a few shots, they can still rambo at you full speed after you shot them +4 times.

**Comment by MrJJJ2** [comment]
Who were you shooting that took more than 4 shots from...what weapon exactly? they might have had armor and that's why they survived, otherwise where the heck where you aiming at? 2 shots can already kill someone if it does organ damage when your aiming for the chest and being hit once slows down you like hell, and i don't think its a realistic for somebody to be pushed down by a luger bullet.

It would make sense with modern day sniper rifles in a way, but bullets don't just make people fall down, sure filling up someone with a SMG could make them fall down, but just shooting once someone in a chest or arms wouldn't make them go down because of RNG, bullets don't have enough force to do that to a person, especially with a neat thing called adrenaline IRL (which can slightly be noticed here if you get into critical state that you can still walk for about a minute or crawl until you just can't do that anymore)

**Comment by Harcourt1** [comment]
I have been shot in the foot by a handgun. (Long story) I does knock you back.

**Comment by MrJJJ2** [comment]
But not enough to actually make you fall down, and remember that adrenaline still exists.

**Comment by Wesreidau** [comment]
#110 is directed at the problem of being shot not having much stopping power.
